### ISSUE TITLE
Not release mode

### ISSUE THREAD

**Issue by yudhaislamisulistya** [lizheming/deta-action#1]
can i set my repo to only push, not release?

**Comment by lizheming** [comment]
This function is not supported yet, if necessary, I can add this configuration in the future.

**Comment by lizheming** [comment]
Hello, I have added `release` option. You just only set `release: false` if you want disable release action. please try it.

**Comment by yudhaislamisulistya** [comment]
Thanks my brother 👍👍👍

**Comment by shubhattin** [comment]
release: false
still not working, getting warning

```
Warning: Unexpected input(s) 'release', valid inputs are ['entryPoint', 'args', 'access_token', 'id', 'tag', 'dir', 'listed', 'notes', 'rid', 'version']
```
and also there is no release option in this schema defined here : https://github.com/lizheming/deta-action/blob/master/action.yml

Please also option for this
